name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      OPEN_WEATHER_API_KEY: ${{ secrets.OPEN_WEATHER_API_KEY }}
      CHAT_GPT_API_KEY: ${{ secrets.CHAT_GPT_API_KEY }}
      GOOGLE_PLACES_API_KEY: ${{ secrets.GOOGLE_PLACES_API_KEY }}

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode google-services.json
      run: |
        echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > app/google-services.json

    - name: Decode jjin-weather-e503bd34a192.json
      run: |
        echo "${{ secrets.GOOGLE_TRANSLATE_JSON_BASE64 }}" | base64 --decode > app/src/main/assets/jjin-weather-e503bd34a192.json

    - name: Build with Gradle
      run: ./gradlew build
